(function(l,m,n){l.execute(function(){l.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-util","p13n-sc-math","p13n-sc-lazy-image-loader").register("p13n-sc-list",function(e,f,k,g,h,j){function i(b){var a=this;a.$container=e(b);if(a.$container.attr(c))return!1;a.$container.attr(c,!0);f.state("sims-list",{initialized:"true"});a.$cellListContainer=a.$container.find(".p13n-sc-list-cells-container");a.$cellList=a.$container.find(".p13n-sc-list-cells");a.$buttons=a.$container.find(".p13n-sc-list-show-more-buttons");
a.$showMoreButton=a.$container.find(".p13n-sc-list-button-show-more");a.$hideButton=a.$container.find(".p13n-sc-list-button-hide");a.$showMorePartialOverlay=a.$container.find(".p13n-sc-list-partial-overlay");a.asins=a.$container.data("asins").toString().split(",");a.asinIndex=a.$container.data("asin-index");a.numVisibleRows=d;a.originalItemWidth=a.$cellListContainer.find(".p13n-sc-list-item:first-child").outerWidth(!0);a.originalCellMarginLeft=parseInt(a.$cellListContainer.find(".p13n-sc-list-item").css("margin-left"),
10);a.initialCellContainerHeight=0;a.isInitialLoad=!0;a.calculateColumns();a.adjustColumnWidths();a.fillVisibleProductSlots();a.placeOverlay();a.configureButtons();a.$buttons.removeClass("a-hidden");a.$showMoreButton.bind("click",function(b){a.showMoreWasTapped(b)});a.$showMorePartialOverlay.bind("click",function(b){a.showMoreWasTapped(b)});a.$showMorePartialOverlay.hover(function(){a.$showMoreButton.addClass("p13n-sc-list-buttons-hover")},function(){a.$showMoreButton.removeClass("p13n-sc-list-buttons-hover")});
a.$showMoreButton.hover(function(){a.$showMoreButton.addClass("p13n-sc-list-buttons-hover")},function(){a.$showMoreButton.removeClass("p13n-sc-list-buttons-hover")});a.$hideButton.hover(function(){a.$hideButton.addClass("p13n-sc-list-buttons-hover")},function(){a.$hideButton.removeClass("p13n-sc-list-buttons-hover")});a.$hideButton.bind("click",function(b){a.hideWasTapped(b)});e(m).bind("resize.p13n-sc-list",function(){a.handleResize()});j.loadImages(a.$container);f.trigger("p13n-sc-list:init",a.$container)}
var c="data-p13n-sc-list-initialized",d=2;i.prototype={hasAdditionalProducts:function(){return this.asins.length>this.asinIndex+1},loadAdditionalProducts:function(b){var a=this;if(!a.isLoadingProducts&&a.hasAdditionalProducts()){a.isLoadingProducts=!0;a.$container.attr("data-p13n-sc-list-loading",!0);for(var c=[],d=a.asinIndex+1;d<=a.asinIndex+b&&d<a.asins.length;d++)c.push(this.asins[d]);(b=this.$container.data("ajax-params"))||(b={faceoutTemplateClass:this.$container.data("faceout-template-class"),
widgetTemplateClass:this.$container.data("widget-template-class"),reftagPrefix:this.$container.data("reftag-prefix"),suppressCurrencyImageFormat:this.$container.data("suppress-currency-image-format"),imageWidth:a.$container.data("image-width")||"",imageHeight:a.$container.data("image-height")||"",auiDeviceType:a.$container.data("aui-device-type")});b.lazyLoadImages=1;b.asins=c.join();b.offset=this.asinIndex+1;d=a.$container.data("ajax-url");f.get(d,{params:b,success:function(b){a.handleAjaxComplete(b,
c.length)},error:function(){a.handleAjaxError(c.length)}})}},handleAjaxComplete:function(b,a){this.asinIndex+=a;this.hideLoadingAnimation();if(b&&e.isArray(b)&&b.length>0){var c=e(b.join(""));this.$cellList.append(c);j.loadImages(c)}else g.log.error("List View partial endpoint returned an item that was not an array of cells.");this.isLoadingProducts=!1;this.$container.attr("data-p13n-sc-list-loading",!1);this.showMorePending=!1;this.adjustColumnWidths();this.placeOverlay();this.isInitialLoad||this.fillNextProductSlots()},
handleAjaxError:function(){g.count("p13n:sc:list:desktop:ajax-error",(g.count("p13n:sc:list:desktop:ajax-error")||0)+1);this.hideLoadingAnimation();this.isLoadingProducts=!1;this.$container.attr("data-p13n-sc-list-loading",!1);if(this.showMorePending)this.numVisibleRows=h.max(d,this.numVisibleRows-3),this.animateClosed(this.getCellContainerHeights().cellContainerHeight),this.showMorePending=!1},visibleSlotsAreFilled:function(){return h.min(this.numVisibleRows*this.numColumns,this.asins.length)-(this.asinIndex+
1)<=0},fillVisibleProductSlots:function(){var b=h.min(this.numVisibleRows*this.numColumns,this.asins.length)-(this.asinIndex+1);if(b>0&&!this.isLoadingProducts){for(var a=0;a<b;a++)this.addLoadingAnimation();this.loadAdditionalProducts(b)}},fillNextProductSlots:function(){var b=h.min(3*this.numColumns,this.asins.length-(this.asinIndex+1))-(this.asinIndex+1);if(b>0&&!this.isLoadingProducts){for(var a=0;a<b;a++)this.addLoadingAnimation();this.loadAdditionalProducts(b)}},handleResize:function(){this.calculateColumns();
this.adjustColumnWidths();this.fillVisibleProductSlots();this.placeOverlay();this.configureButtons();f.trigger("p13n-sc-list:resize",this)},calculateColumns:function(){var b=this.$cellListContainer.width();this.numColumns=h.floor(b/this.originalItemWidth);this.cellMarginLeft=this.originalCellMarginLeft+(h.floor((b-this.originalItemWidth*this.numColumns)/this.numColumns)-5)},getNumPossibleRows:function(){return h.ceil(this.asins.length/this.numColumns)},adjustColumnWidths:function(){this.$cellListContainer.find(".p13n-sc-list-item").css("margin-left",
this.cellMarginLeft)},getCellContainerHeights:function(){if(this.numVisibleRows>=this.getNumPossibleRows()&&!this.isInitialLoad)return{cellContainerHeight:this.$cellList.height(),lastRowPixels:0};for(var b=this.$cellList.children(),a=b.first().offset().top,c=0,d=0,f=0,e=0;e<b.length;e++){var i=b.eq(e).offset().top,h=b.eq(e).outerHeight(!0);if(i>a){c+=1;if(c===this.numVisibleRows)break;d+=f;f=h;a=i}else h>f&&(f=h)}c>=this.numVisibleRows||c>=1&&(this.hasAdditionalProducts()||this.isInitialLoad)?(b=
d+55,a=55):(b=d+f,a=0);return{cellContainerHeight:b,lastRowPixels:a}},placeOverlay:function(){var b=this.getCellContainerHeights();this.cellContainerHeight=b.cellContainerHeight;this.$cellListContainer.css({height:this.cellContainerHeight,overflow:"hidden"});this.$showMorePartialOverlay.css({height:b.lastRowPixels,top:-b.lastRowPixels})},showMoreWasTapped:function(){this.isInitialLoad=!1;f.trigger("p13n-sc-list:show-more",this);g.count("p13n:sc:list:desktop:show-more",(g.count("p13n:sc:list:desktop:show-more")||
0)+1);this.numVisibleRows=h.min(this.numVisibleRows+3,this.getNumPossibleRows());if(!this.visibleSlotsAreFilled())this.showMorePending=!0,this.fillVisibleProductSlots();this.animateOpen(this.getCellContainerHeights().cellContainerHeight)},hideWasTapped:function(){g.count("p13n:sc:list:desktop:hide",(g.count("p13n:sc:list:desktop:hide")||0)+1);this.numVisibleRows=d;this.animateClosed(this.getCellContainerHeights().cellContainerHeight)},animateOpen:function(b){var a=this;f.animate(a.$cellListContainer,
{height:b},1E3,"cubic-bezier(0.86, 0, 0.07, 1)",function(){a.configureButtons();a.placeOverlay()})},animateClosed:function(b){var a=this;a.$cellListContainer.animate({height:b},{duration:500,queue:!1,complete:function(){a.configureButtons();a.placeOverlay()}});e("html, body").animate({scrollTop:a.$container.offset().top+b+a.$buttons.outerHeight()-e(m).height()+150},{duration:500,queue:!1})},addLoadingAnimation:function(){this.$cellList.append(e('<div class="sims-show-hide p13n-sc-list-item p13n-sc-list-loader a-manually-loaded" style="right: 0px;"></div>'))},
hideLoadingAnimation:function(){this.$cellListContainer.find(".p13n-sc-list-loader").remove()},isAtMaxHeight:function(){return this.numVisibleRows>=this.getNumPossibleRows()},isAtMinHeight:function(){return this.numVisibleRows<=d},configureButtons:function(){var b=this.getNumPossibleRows(),a=2;b===1||b===d&&!this.isInitialLoad?a=3:this.isAtMinHeight()?a=0:this.isAtMaxHeight()&&!this.isLoadingProducts&&(a=1);this.setButtonState(a);this.$buttons.width(this.$cellListContainer.innerWidth())},setButtonState:function(b){this.buttonState=
b;this.$buttons.removeClass("p13n-sc-both-state p13n-sc-show-more-state p13n-sc-hide-state");b===0?(this.$buttons.addClass("p13n-sc-show-more-state"),this.$buttons.show()):b===1?(this.$buttons.addClass("p13n-sc-hide-state"),this.$buttons.show()):b===2?(this.$buttons.addClass("p13n-sc-both-state"),this.$buttons.show()):b===3&&this.$buttons.hide()}};f.on("afterReady",function(){e(".p13n-sc-list").each(function(b,a){new i(a)})});f.state.bind("sims-list",function(){e(".p13n-sc-list").each(function(b,
a){new i(a)})});return i});l.when("A","jQuery","p13n-sc-call-on-visible","p13n-sc-logger","afterReady").execute("sims-list-logger",function(e,f,k,g){function h(e){k.register(e,function(){g.logAsyncAction(f.extend(!0,{},{featureElement:e,isEventComplete:function(){return!e.attr(j)},replicateAsinImpressions:!0},{action:"view"}))})}var j="data-p13n-sc-list-loading";f(".p13n-sc-list").each(function(e,c){var d=f(c);d.attr("data-p13n-sc-list-initialized")&&h(d)});e.on("p13n-sc-list:init",function(e){h(e)});
e.on("p13n-sc-list:show-more",function(e){g.logAsyncAction(f.extend(!0,{},{featureElement:e.$container,isEventComplete:function(){return!e.isLoadingProducts},replicateAsinImpressions:!0},{action:"show_more"}))});e.on("p13n-sc-list:resize",function(e){e.$container.attr("data-p13n-sc-list-initialized")&&g.logAsyncAction(f.extend(!0,{},{featureElement:e.$container,isEventComplete:function(){return!e.isLoadingProducts},replicateAsinImpressions:!0},{action:"resize"}))})});l.when("jQuery","A").execute("sims-bind-parse-aui",
function(e,f){function k(){var h=f.parseJSON;f.each(e('script[type="a-state"]'),function(j){j=e(j);if(!j.data("a-eval")){var i=j.attr("data-a-state");if(i&&(i=h(i),i.key&&e.inArray(i.key,g)!==-1)){var c=h(j.html());f.state.replace(i.key,c);j.data("a-eval",!0)}}})}var g=["sims-fbt","sims-list"];f.on("a:pageUpdate",function(){k()})});(function(){l.when("jQuery","A","p13n-sc-line-truncator").register("sims-carousel-truncation",function(e,f,k){for(var e=["purchase","session"],g=e.length-1;g>=0;g--)f.on("a:carousel:"+
e[g]+":change:animating",function(e){k.truncateLines(e.carousel.dom.$container)}),f.on("a:carousel:"+e[g]+":change:loading",function(e){k.truncateLines(e.carousel.dom.$container)}),f.on("a:carousel:"+e[g]+":change:pageSize",function(e){k.truncateLines(e.carousel.dom.$container)})})})(m,document,m.ueLogError);l.when("jQuery","A","a-checkbox","p13n-sc-util","p13n-sc-call-on-visible","p13n-sc-logger").execute("sims-fbt",function(e,f,k,g,h,j){function i(c){var d=this,b=c.data("sims-fbt-instance");if(b)return b;
c.data("sims-fbt-instance",d);d.hasLazyInitialized=!1;e(".sims-fbt-checkbox input").show();d.$fbtRootElement=c;d.$detailsLinkText=d.$fbtRootElement.find(".sims-fbt-details-link a");d.auiCheckboxes=[];b=this.$fbtRootElement.find("div.sims-fbt-checkbox");this.numOfItems=b.length;for(var a=0;a<this.numOfItems;a++)this.auiCheckboxes[a]=k(b[a]),this.auiCheckboxes[a].check();f.declarative.remove(d.$detailsLinkText,"details-link-click");f.declarative.remove(e(".sims-fbt-details-help-link"),"help-link-click");
f.declarative.create(d.$detailsLinkText,"details-link-click");f.declarative.create(e(".sims-fbt-details-help-link"),"help-link-click");var g=e("#sims-fbt-container");h.register(c,function(){j.logAction({featureElement:g,action:"view",replicateAsinImpressions:!0,meta:{numsims:d.numOfItems}})});return d}i.prototype={lazyInitialize:function(){if(!this.hasLazyInitialized){this.$priceBlock=this.$fbtRootElement.find(".sims-fbt-price-box");this.$totalPriceDiv=this.$priceBlock.find(".sims-fbt-total-price");
this.$addToCartButton=this.$priceBlock.find(".sims-fbt-add-to-cart");this.$addToWishlistButton=this.$priceBlock.find(".sims-fbt-add-to-wishlist");this.$sellerInfo=this.$fbtRootElement.find(".sims-fbt-seller-info");this.$detailsText=this.$fbtRootElement.find(".sims-fbt-shipping-details-text");this.haveDetails=this.$detailsText.length!==0;try{this.FBTData=f.state("sims-fbt")}catch(c){g.log.error("[sims-fbt] Unable to find Data Attribute (page state) "+c);return}this.images=[];this.plusSigns=[];for(var d=
0;d<this.numOfItems;d++)this.images[d]=this.$fbtRootElement.find(".sims-fbt-image-"+(d+1)),d>0&&(this.plusSigns[d]=this.$fbtRootElement.find(".sims-fbt-plus-"+(d+1)));this.hasLazyInitialized=!0}},toggleSellerInfo:function(){this.lazyInitialize();var c=this.$sellerInfo.is(":hidden");c||this.$sellerInfo.hide();this.updateSellerText(c);c&&this.$sellerInfo.show(200)},handleCheckboxChange:function(c){var d=c.$declarativeParent,b=c.data,a=parseInt(b.itemNum,10);this.lazyInitialize();this.auiCheckboxes[a-
1].disable();c=this.$priceBlock;this.auiCheckboxes[a-1].isUnchecked()&&(c=c.add(this.handleItemUnchecked(d,b,a)));var e=this;c.fadeOut(function(){e.handleItemChecked(d,b,a)})},handleItemChecked:function(c,d,b){this.updateButtons(c);this.updateTotalPrice(c);this.updateSellerText(this.$sellerInfo.is(":visible"));if(this.findFirstCheckedItem()>=0){d=this.$priceBlock;this.auiCheckboxes[b-1].isChecked()&&(c.find(".sims-fbt-checkbox-label").removeClass("sims-fbt-unselected-item"),c=this.findFirstVisibleItem(),
c>=1&&(b>c?d=d.add(this.plusSigns[b-1]):b<c&&(d=d.add(this.plusSigns[c-1]))),d=d.add(this.images[b-1]));var a=this;d.fadeIn(function(){a.auiCheckboxes[b-1].enable()})}else this.auiCheckboxes[b-1].enable()},handleItemUnchecked:function(c,d,b){c.find(".sims-fbt-checkbox-label").addClass("sims-fbt-unselected-item");c=this.images[b-1];b>1&&(c=c.add(this.plusSigns[b-1]));b=this.findFirstCheckedItem();b>1&&(c=c.add(this.plusSigns[b-1]));return c},findFirstVisibleItem:function(){for(var c=1;c<=this.numOfItems;c++)if(this.images[c-
1].is(":visible"))return c;return-1},findFirstCheckedItem:function(){for(var c=1;c<=this.numOfItems;c++)if(this.auiCheckboxes[c-1].isChecked())return c;return-1},updateButtons:function(){for(var c=this.getOfferListingIDsSeletected(),d=1,b="preOrderText",a=c.length-1;a>=0;a--)if(!this.FBTData.itemDetails[c[a]].isPreorder){b="addToCartText";d=0;break}d?this.$addToCartButton.removeClass("a-button-primary").addClass("a-button-preorder"):this.$addToCartButton.removeClass("a-button-preorder").addClass("a-button-primary");
c.length>=1?(this.$addToCartButton.find(".a-button-text").text(this.FBTData[b][c.length]),this.$addToCartButton.attr("disabled")&&(this.$addToCartButton.removeClass("a-button-disabled"),this.$addToCartButton.removeAttr("disabled")),this.$addToWishlistButton.find(".a-button-text").text(this.FBTData.addToWishListText[c.length]),this.$addToWishlistButton.attr("disabled")&&(this.$addToWishlistButton.removeClass("a-button-disabled"),this.$addToWishlistButton.removeAttr("disabled"))):(this.$addToCartButton.find(".a-button-text").text(this.FBTData.addToCartText[1]),
this.$addToCartButton.addClass("a-button-disabled"),this.$addToCartButton.attr("disabled","disabled"),this.$addToWishlistButton.find(".a-button-text").text(this.FBTData.addToWishListText[1]),this.$addToWishlistButton.addClass("a-button-disabled"),this.$addToWishlistButton.attr("disabled","disabled"))},updateTotalPrice:function(){var c=this.getOfferListingIDsSeletected(),d=0,b=0,a=0,e=0;if(c.length===0)this.$totalPriceDiv.hide();else{for(var f=0;f<c.length&&!e;f++){if(this.FBTData.itemDetails[c[f]].doesMAPPolicyApply){e=
1;break}else isFinite(this.FBTData.itemDetails[c[f]].price)&&(d+=parseFloat(this.FBTData.itemDetails[c[f]].price,10));isFinite(this.FBTData.itemDetails[c[f]].points)&&(b+=parseInt(this.FBTData.itemDetails[c[f]].points,10),a+=parseFloat(this.FBTData.itemDetails[c[f]].pointsValue,10))}this.$totalPriceDiv.show();c=this.$totalPriceDiv.find(".sims-fbt-total-price-value");e?(c.html(this.FBTData.MAPText),c.removeClass("a-color-price").addClass("sims-fbt-map-text").addClass("a-size-base")):(e=this.FBTData.currencySymbol,
e+=this.formatPrice(d),c.html(e),c.removeClass("sims-fbt-map-text").addClass("a-color-price").removeClass("a-size-base"));e=this.$totalPriceDiv.find(".sims-fbt-points-wrapper");b>0?(d=parseInt(a*100/d+0.5,10),a=e.find(".sims-fbt-points-value"),c=e.find(".sims-fbt-points-percentage"),a.html(b),c.html(d),e.show()):e.hide()}},getOfferListingIDsSeletected:function(){var c=[];e("input",".sims-fbt-checkbox").each(function(){this.checked&&c.push(this.value)});return c},formatPrice:function(c){for(var d=
(c-parseInt(c,10)).toFixed(2),d=d.replace("0.","."),b=parseInt(c,10),a=0;b>0;){var e=b%10,b=parseInt(b/10,10),d=e.toString()+d;a++;a%3===0&&b>0&&(d=","+d)}this.FBTData.currencyCode==="EUR"?(d=d.replace(/,/,"+"),d=d.replace(/\./,","),d=d.replace(/\+/,".")):this.FBTData.currencyCode==="JPY"&&(d=d.replace(".00",""));Math.abs(c)<1&&(d="0"+d);return d},updateSellerText:function(c){var d="",b="",a="",a=0;if(this.haveDetails){for(b=1;b<=this.numOfItems;b++)this.auiCheckboxes[b-1].isChecked()&&(d+=b,a++);
b=a===0?this.getString("noDetails"):a===1?"":this.FBTData.shippingDetails[d]==="seller"?this.getString("differentSellers"):this.FBTData.shippingDetails[d]==="availabilityone"?this.getString("differentAvailabilityOne"):this.FBTData.shippingDetails[d]==="availabilitysome"?this.getString("differentAvailabilitySome"):"";a=a===0?"":b===""?this.getString(c?"hideDetailsLong":"showDetailsLong"):this.getString(c?"hideDetails":"showDetails");b!==this.$detailsText.text()&&this.$detailsText.text(b);a!==this.$detailsLinkText.text()&&
this.$detailsLinkText.text(a)}},getString:function(c){return this.FBTData&&this.FBTData.fbtStrings?this.FBTData.fbtStrings[c]:n}};(function(){function c(){return e("#sims-fbt-content").data("sims-fbt-instance")}function d(){var b=e("#sims-fbt-content");b.length&&new i(b)}f.declarative("help-link-click","click",function(b){b.$event.preventDefault();m.open(b.$event.target.href,"AmazonHelp","width=550,height=550,resizable=1,scrollbars=1,toolbar=0,status=0").focus();return!1});f.declarative("details-link-click",
"click",function(b){b.$event.preventDefault();(b=c())&&b.toggleSellerInfo()});f.declarative("fbt-checkbox-click","change",function(b){var a=c();a&&a.handleCheckboxChange(b)});f.state.bind("sims-fbt",d);f.on("afterReady",d)})()});l.when("jQuery","A","p13n-sc-call-on-visible").register("sims-client-side-weblab",function(e,f,k){function g(f){var g=0,i={cache:!0,crossDomain:!1,data:e.param(f,!1),error:function(d){d=d.status||0;g>=3||d>=400&&d<500||setTimeout(c,200*Math.pow(2,g))},global:!1,url:"/gp/similarities/record.html"},
c=function(){g+=1;e.ajax(i)};c()}f.on.ready(function(){var h={"#view_to_purchase-sims-feature":"view_to_purchase-sims-weblab-state"},j;for(j in h)if(h.hasOwnProperty(j)){var i=e(j);i.length>0&&k.register(i,function(){var c=f.state(h[j]);c&&g(c)})}})});l.when("A","jQuery","p13n-sc-call-on-visible","p13n-sc-logger").execute("sims-vtp-logger",function(e,f,k,g){var h=f(".vtp-container");h.length>0&&k.register(h,function(){g.logAction({featureElement:h,action:"view",replicateAsinImpressions:!0})})})})})(function(){var l=
window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors;return m?m("SimilaritiesUDPTransistionAssets"):l}(),window);
/* ******** */
(function(b){b.execute(function(){b.when("jQuery","jumpLink").execute(function(b,a){var k=b("#miniATFUDP"),f=0;k.length>0&&(f=k.height()+9);window.isACRJumplLinkAnimated===1?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",1E3,f):window.isACRJumplLinkAnimated===2?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",1200,f):window.isACRJumplLinkAnimated===3?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",
1400,f):window.isACRJumplLinkAnimated===4?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",10,f):k.length>0&&(f=k.height()+9,a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",10,f))});b.when("A","jQuery","ImageBlockATF","jumpLink").register("miniATFUtils",function(l,a,k,f){function u(d){o&&!d||p||(d=(new Date).getTime()-v,d=d<50?50-d:10,o=1,o=0,v=(new Date).getTime(),setTimeout(function(){var d=
m.scrollTop(),b=a("#miniATFUDP");if(b.length>0){var c=w;if(c==="T1"){c=a("#sims_fbt");if(c.length<=0||c.height()<=0)c=a("#buyxgety_feature_div");var g=c,c=Number.MAX_VALUE;if(g&&g.length>0){var i=g.height(),g=g.offset();i&&g&&(c=g.top+i)}c=Math.min(c,y)}else if(c==="T2"){c="#product-details-grid_feature_div,#prodDetails,#important-information_feature_div,#importantInformation,#detail-bullets,#detail_bullets_id,#technical-data,#technicalSpecifications_feature_div,#productDescription,#product-description-iframe,#dpx-btf-hlcx-comparison_feature_div,#HLCXComparisonWidget_feature_div".split(",");
g=Number.MAX_VALUE;for(i=0;i<c.length;i++){var e=a(c[i]);if(e&&e.length>0&&e.height()>0){var h;h=Number.MAX_VALUE;if(e&&e.length>0&&(e=e.offset()))h=e.top;h<g&&(g=h)}}c=Math.min(g,z)-100}else c=void 0;d>c?!q&&b.is(":hidden")&&(b.removeClass("a-hidden"),b.slideDown(A)):(b.slideUp(B),q=0)}},d))}var r=a("#miniATFUDP"),x=a("#miniATFPartialSelection")[0],j=a(".twister-dropdown-highlight")[0];if(!(r.length<=0)){var m,q=0,v=0,o=0,n={},p=0,B=200,A=200,y=1200,z=1700,s=0,w="T1";n.setMiniATFShowHeight=function(a){w=
a};n.setMiniATFScrollUpHeight=function(d){s=0;d==="T1"&&(d=a("#productTitle"),d.length>0&&(d=d.offset())&&(s=d.top-20))};a("body").delegate(".go-to-top","click",function(){a("body, html").animate({scrollTop:s},300);q=1;x&&j&&(a(j).removeClass("transparentTwisterDropdownBorder"),a(j).addClass("highlightTwisterDropdownBorder"));return!1});x&&j&&a(j).click(function(){a(this).addClass("transparentTwisterDropdownBorder");a(this).removeClass("highlightTwisterDropdownBorder")});m=a(window);m.scroll(function(){u(0)});
m.resize(function(){u(1)});var t=0;r.length>0&&(t=r.height()+9,f.bind("#seeMoreDetailsLink",300,t),f.bind("#HLCXComparisonJumplinkLink",300,t));b.when("ImageBlockBTF","imageBlockUtils").execute(function(d){var b=function(h){var c=h.getState().selected_variations;if(c){var b="",f=h.getState().variation_display_labels;a.each(d.visualDimensions,function(a,h){var g=d.gIsNewTwister===1?h:f[h];c[g]&&(b+=" "+c[g])});return b&&b.substring(1)}},f=d.defaultColor,c=f,g=d.landingAsinColor,i,e=a("#miniATF_image");
e.length>0&&(i=e.attr("src"));n.updateMiniATFDiv=function(){p=0;var h=a("#miniATF_image");h.length>0&&i&&h.attr("src",i)};l.on("image-block-twister-swatch-click",function(a,e,l,j){p=1;a=(a=j?j:b(e))&&a!==""?a:f;a===g&&(a=f);a!==c&&(i=(e=a!==f&&a!==g?d:k)&&e.colorImages&&e.colorImages[a]&&e.colorImages[a].length>0&&e.colorImages[a][0]?e.colorImages[a][0].large:null,c=a)})});return n}});b.when("ueCount","jQuery").execute(function(b,a){a("#miniATF_BackToTopLink").click(function(){b.incrementCounterByOne("sl_back_to_top_button_click_count")})})})})(function(){var b=
window.AmazonUIPageJS||P,l=b.attributeErrors;return l?l("CommonDetailPageScripts"):b}());
/* ******** */
(function(a){a.execute(function(){a.when("A","jQuery").register("jumpLink",function(a,c){return{bind:function(a,e,f){try{e=e||1E3,f=f||0,c("body").delegate(a,"click",function(b){try{var g=c(a);if(g.get(0)){var d=g.attr("href");d&&d.charAt(0)==="#"&&c(d).length!==0&&(b.preventDefault(),c("html, body").animate({scrollTop:c(d).offset().top-f},e))}}catch(h){window.ueLogError&&window.ueLogError(h,{logLevel:"FATAL",attribution:"jumpLink",message:"[JumpLink - Error in executing click handler]"})}})}catch(b){window.ueLogError&&
window.ueLogError(b,{logLevel:"FATAL",attribution:"jumpLink",message:"[JumpLink - Error in binding click handler]"})}}}})})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("DetailPageCommonScripts"):a}());
/* ******** */
(function(i,k){i.execute(function(){i.when("A","jQuery","ready").register("DeliveryCountdownComponent",function(c,b){function h(b,c,f,a,e){this.strings=b;this.asin=c;this.deliveryMessageSectionId=f;this.countdownElementId=a;this.secondsLeft=e;this.intervalHandle=null}k.DeliveryCountdownHandler=function(b){var c=b.strings,f=b.asin,a=b.deliveryMessageSectionId,e=b.fastCountdownElementId,i=b.cheapCountdownElementId;this.cheapCountdownTimer=this.fastCountdownTimer=null;this.start=function(b,d){if(b>0)this.fastCountdownTimer=
new h(c,f,a,e,b),this.fastCountdownTimer.start();if(d>0)this.cheapCountdownTimer=new h(c,f,a,i,d),this.cheapCountdownTimer.start()};this.stop=function(){if(this.fastCountdownTimer)this.fastCountdownTimer.stop(),this.fastCountdownTimer=null;if(this.cheapCountdownTimer)this.cheapCountdownTimer.stop(),this.cheapCountdownTimer=null}};h.prototype.start=function(){var b=this;this.intervalHandle=c.interval(function(){b&&b.updateCountdownText()},1E3)};h.prototype.stop=function(){this.intervalHandle&&k.clearInterval(this.intervalHandle)};
h.prototype.updateCountdownText=function(){this.secondsLeft--;if(this.secondsLeft>0){var c=Math.floor(this.secondsLeft/60),g=c%60,c=Math.floor(c/60),f=this.secondsLeft%60,a=this.strings.inNext,e=c>1?this.strings.hours:this.strings.hour,h=g>1?this.strings.minutes:this.strings.minute,i=f>1?this.strings.seconds:this.strings.second,k=this.strings.timeSeperator;b(this.countdownElementId).html(c>0&&g>0?c+k+e+k+g+k+h+k+a:c>0&&g===0?c+k+e+a:c===0&&g>0?g+k+h+a:f+k+i+a)}else this.stop(),g="<a href='javacript:window.location.reload();'>"+
this.strings.refreshTimeout+"</a>",b(this.deliveryMessageSectionId).html(g)}});i.when("A","jQuery","LUXContext").register("LUXController",function(c,b,h){function d(){return{addressLabel:j,addressId:F,obfuscatedId:z,countryCode:s,zipCode:t,state:r,city:p,district:u,locationType:x}}function g(a){j=a.addressLabel;F=a.addressId;z=a.obfuscatedId;s=a.countryCode;t=a.zipCode;r=a.state;p=a.city;u=a.district;x=a.locationType}function f(a,b,f){a=c.copy(a);a.deviceType=h.deviceType;a.pageType=e;c.post(B,{contentType:"application/x-www-form-urlencoded;charset=utf-8",
params:a,success:function(a){if(a.sembuUpdated){a.address&&g(a.address);var e=d();c.trigger(m,e);c.trigger(k,e);b&&b();i.when("LUXMetrics").execute(function(a){a.logLocationChange(e.locationType)})}else f&&f()},error:function(){c.trigger(l,d());f&&f()}})}var a=!1,e=null,k="DeliveryAddressDropdown_OnAddressChange",m="DeliveryAddressDropdown_OnSembuUpdateSuccess",l="DeliveryAddressDropdown_OnSembuUpdateFail",j,F,z,s,t,r,p,u,x,B="/gp/delivery/ajax/address-change.html";return{locationChangeEventName:k,
locationTypes:{defaultAddress:"DEFAULT_ADDRESS",accountAddress:"ACCOUNT_ADDRESS",lockerAddress:"LOCKER_ADDRESS",locationInput:"LOCATION_INPUT",realmDefault:"REALM_DEFAULT",region:"REGION",country:"COUNTRY",ip2location:"IP2LOCATION"},init:function(b){i.when("LUXResponder").execute(function(e){a?c.equals(b,d())||(g(b),e.refresh()):(g(b),e.activate(),a=!0)});i.when("LUXCustom").execute(function(a){a.activate()});i.when("LUXMetrics").execute(function(a){e=a.getPageType()})},getLocationData:function(){return d()},
changeLocation:function(a,b,c){f(a,b,c)}}});i.when("A","LUXDPOnly").register("LUXDPRefreshController",function(c){function b(b){e=b;h({addressId:e.addressId,zipCode:e.zipCode,city:e.city,state:e.state,district:e.district,countryCode:e.countryCode});var c={asin:e.asin,merchantId:e.merchantId,deviceType:e.deviceType,smid:e.smid,exMerchId:e.exMerchId};e.useTwisterRefresh==="T1"&&i.when("TwisterUpdateHandler").execute(function(b){b.init(c);f=!0;a=b});i.when("UnifiedLocationUpdateHandler").execute(function(b){f||
(b.init(c),a=b)});d(e.obfuscatedId)}function h(a){var b=1;g("#quantity").length===1&&(b=g("#quantity").val());c.state("unifiedLocation",{addressId:a.addressId,zipCode:a.zipCode,city:a.city,state:a.state,district:a.district,countryCode:a.countryCode,quantity:b})}function d(a){if(e&&e.oneClick){if(!a)a=e.addNewAddress;var b="#unifiedLocation1ClickAddress";e.deviceType&&e.deviceType==="mobileApp"&&(b="#addressID");g(b).length===1&&g(b).val(a);if(e.deviceType&&e.deviceType in k&&(b=c.state("buyNowInfo"))){var d=
b.urlParams,d=d.indexOf("addressID=")>0?d.replace(/(addressID=)[^&]*/,"$1"+a):d+"&addressID="+a;b.urlParams=d;c.state("buyNowInfo",b)}}}var g=c.$,f=!1,a=null,e=null,k={tabletApp:1,tabletLargeApp:1,iPad:1};c.on("DeliveryAddressDropdown_OnAddressChange",function(b){h(b);d(b.obfuscatedId);a!==null&&(a.refresh(),f||c.trigger("LocationUX_OnAddressChange",b))});return{init:function(a){b(a)}}});i.when("A","detailPage:RefreshHandler","LUXDPOnly","a-state").execute(function(c,b){i.register("TwisterUpdateHandler",
function(){return{init:function(b){c.state("unifiedLocation",b)},refresh:function(){var h=b.getHandlerInstance("LocationUX"),d=[],g="addressId,zipCode,city,state,district,countryCode".split(",");if(h){var f=c.state("unifiedLocation"),a;for(a in f)if(f.hasOwnProperty(a)&&c.$.inArray(a,g)>-1){var e=typeof f[a];if(e==="number"||e==="boolean"||e==="string"||f[a]instanceof String)d.push(h.getURLParamObject(a,f[a]===null?"":f[a],1))}}d.length>0&&h.doPageRefresh(d)}}})});i.when("A","LUXDPOnly","a-state").execute(function(c){i.register("UnifiedLocationUpdateHandler",
function(){return{init:function(a){c.state("unifiedLocation",a)},refresh:function(){b=2;h()}}});var b=0,h=function(){var a=c.state("unifiedLocation"),b;for(b in a)if(a.hasOwnProperty(b)){var h=typeof a[b];h==="number"||h==="boolean"||h==="string"||a[b]instanceof String||(a[b]===null?a[b]="":delete a[b])}a&&a.asin&&a.merchantId&&(c.trigger("UnifiedLocationPreRefresh"),c.ajax("/gp/product/features/unified-location/udp/refresh-features.html?_encoding=UTF-8",{params:a,method:"POST",success:d,error:g,
abort:f}))},d=function(){c.trigger("UnifiedLocationPostRefresh",!0)},g=function(){c.trigger("UnifiedLocationPostRefresh",!1);--b>0&&h()},f=function(){c.trigger("UnifiedLocationPostRefresh",!1)}});i.when("A","jQuery","a-popover","LUXWidgetConfig","ready").execute(function(c,b,h,d){function g(g){var h=!1,D=g.selectedAddressId,v=g.selectedObfuscatedId,E=g.selectedAddressLabel,H=g.selectedCountryCode,N=g.selectedZipCode,C=g.selectedState,w=g.selectedCity,o=g.selectedDistrict,q=g.addressPopover.name,y=
g.addressPopover.type,J=d.initialAddressLoadCount,K=d.addressReloadCount,A=g.deviceType,L=g.isRecognized,I=0,M=!1;this.init=function(){h||(h=!0,U())};this.destroy=function(){c.off("a:popover:beforeShow:"+q,T);c.off("a:popover:afterHide:"+q,R);c.capabilities.tablet&&b.isFunction(c.off.orientationchange)&&c.off.orientationchange(X);b(document).undelegate(n,"focus");b(document).undelegate(n,"input");b(document).undelegate(r,"click");b(document).undelegate(e,"click");b(document).undelegate(l+" input[type=radio], "+
p+" ul li .a-touch-link.a-touch-select","click");b(document).undelegate(s,"click")};var G=function(){i.when(y).execute(function(a){a.get(q)&&a.get(q).hide()})},U=function(){c.on("a:popover:beforeShow:"+q,T);c.on("a:popover:afterHide:"+q,R);c.capabilities.tablet&&b.isFunction(c.on.orientationchange)&&c.on.orientationchange(X);b(document).delegate(n,"focus",function(){$()});b(document).delegate(r,"click",function(){var a=!0;A==="mobileApp"&&i.now("mash").execute(function(b){b&&(a=!1,b.navstack.begin().back().end(),
b.showLoginDialog({successCallback:function(){b.navstack.begin().back().forward(k.location.href).end()}}))});if(a)k.location.href=g.addressPopover.signInURL+k.location.pathname});b(document).delegate(n,"input",function(){Q()});b(document).delegate(n,"keypress",function(a){(a.keyCode||a.which)===13&&S()});b(document).delegate(e,"click",function(){S()});b(document).delegate(l+" input[type=radio], "+p+" ul li .a-touch-link.a-touch-select","click",function(){var a=b.parseJSON(b(this).hasClass("a-touch-link")?
b(this).find("input[type=hidden]").val():b(this).val());if(b(this).hasClass("a-active"))G();else if(a){var c=a.id;c!==D&&aa({addressId:c,isDefaultShippingAddress:a.isDefault,addressLabel:a.label,deviceType:A},!1,b(this))}});b(document).delegate(s,"click",function(){Y()});A==="tabletApp"&&k.scrollBy(0,1)},V=b(n).attr("placeholder"),Q=function(){A==="tabletApp"&&(b(n).val()?b(n).removeAttr("placeholder"):b(n).attr("placeholder",V))},S=function(){var a=b(n).val();!a||!a.match(/^\d{5}$/)?Z():aa({zipCode:a,
deviceType:A},!0,null)},T=function(){b(m).hasClass("aok-hidden")||(b(n).val(""),$());c.capabilities.tablet&&b("#a-popover-lgtbox")&&b("#a-popover-lgtbox").css({position:"absolute",top:"0px",left:"0px",width:"100%",height:b("#a-page").css("height")});Q();M||Y()},R=function(){A==="tabletApp"&&document.activeElement.blur()},X=function(){i.when(y).execute(function(a){a.get(q)&&a.get(q).refresh()})},Y=function(){L&&b.ajax({type:"POST",url:f,contentType:"application/x-www-form-urlencoded;charset=utf-8",
data:{currentAddressCount:I,loadCount:M?K:J,selectedAddressId:D,deviceType:A},dataType:"json",success:function(a){if(a){var c=a.loadedAddressCount;if(c>0){var d=a.html;d&&(b(p).length?(b(p+" ul li").has("span .a-touch-link.a-touch-select").remove(),b(p+" ul").html(d+b(p+" ul").html())):b(l).html(d),b(j).removeClass("a-hidden aok-hidden"),b(F).addClass("aok-hidden"),b(t).removeClass("a-hidden aok-hidden"),i.when(y).execute(function(a){a.get(q)&&a.get(q).updatePosition()}),a.hasMore?b(s).removeClass("a-hidden aok-hidden"):
b(s).addClass("aok-hidden"),I=c)}}M=!0},error:function(){}})},Z=function(){b(n).addClass("a-form-error");b(m).removeClass("a-hidden aok-hidden");A==="tabletApp"&&(document.activeElement.blur(),b(m)[0].scrollIntoView())},$=function(){b(n).removeClass("a-form-error");b(m).addClass("aok-hidden")},aa=function(c,d,e){b.ajax({type:"POST",url:a,contentType:"application/x-www-form-urlencoded;charset=utf-8",data:c,dataType:"json",success:function(a){if(a.sembuUpdated){if(a=a.address)D=a.addressId,v=a.obfuscatedId,
E=a.addressLabel,H=a.countryCode,N=a.zipCode,C=a.state,w=a.city,o=a.district,a="",a=E?E:(w?w+", ":"")+(C?C+" ":"")+N,b(z).html(a),d&&(b(l+" input[type=radio]:checked").attr("checked",!1),b(n).val("")),b(p+" ul li .a-touch-link.a-touch-select.a-active").removeClass("a-active"),e&&e.hasClass("a-touch-link")&&e.addClass("a-active");G();W(x);W(u)}else a.isValidAddress||Z()},error:function(){W(B)}})},W=function(a){c.trigger(a,{addressId:D,obfuscatedId:v,countryCode:H,zipCode:N,state:C,city:w,district:o})}}
var f="/gp/delivery/ajax/get-customer-address-list.html",a="/gp/delivery/ajax/address-change.html",e="#unifiedLocationAddrUpdate",n="#unifiedLocationAddrInput",m="#unifiedLocationInvalidInputAlert",l="#unifiedLocationAccountAddrList",j="#unifiedLocationTitleSelectAddress",F="#unifiedLocationTitleNoAddress",z="#unifiedLocationSelectedAddressText",s="#unifiedLocationSeeMore",t="#unifiedLocationSeeMoreDiv",r="#unifiedLocationSignIn",p="#unifiedLocationPopoverSelections",u="DeliveryAddressDropdown_OnAddressChange",
x="DeliveryAddressDropdown_OnSembuUpdateSuccess",B="DeliveryAddressDropdown_OnSembuUpdateFail";i.register("DeliveryAddressDropdown",function(){var a;return{init:function(b){a&&a.destroy();(a=new g(b)).init()}}})});i.when("A","jQuery","LUXContext","LUXWidgetConfig","LUXUtils","LUXController","LUXMetrics","ready").register("LUXResponder",function(c,b,h,d,g,f,a){function e(a){a===J?(b(w).addClass("a-form-error"),b(o).width(b(o).parent().width()).removeClass("aok-hidden"),b(q).addClass("aok-hidden")):
a===K?(b(w).removeClass("a-form-error"),b(o).addClass("aok-hidden"),b(q).width(b(q).parent().width()).removeClass("aok-hidden")):a===A&&(b(w).removeClass("a-form-error"),b(o).addClass("aok-hidden"),b(q).addClass("aok-hidden"))}function n(a){b(O).html(g.generateLocationLabel(a))}function m(a){b(D+" input[type=radio]:checked").attr("checked",!1);for(var d=b(D+" .a-declarative").has(".a-radio input[type=radio]"),a=a.addressId,e=d.length-1;e>=0;e--)if(c.parseJSON(d[e].getAttribute(y)).addressId===a){b(".a-radio input[type=radio]",
d[e]).attr("checked",!0);break}}function l(a){a.locationType===f.locationTypes.locationInput&&a.zipCode?b(w).val(a.zipCode):b(w).val("");e(A)}function j(a){i.when("a-dropdown").execute(function(b){b=b.getSelect(d.countrySelectorComponentName);c.objectIsEmpty(b)||(a.locationType===f.locationTypes.country||a.locationType===f.locationTypes.region||a.locationType===f.locationTypes.ip2location&&!a.state?b.setValue(g.mapLocationDataToCode(a)):b.setValue(""))})}function F(){c.post(P,{contentType:"application/x-www-form-urlencoded;charset=utf-8",
params:g.prepareCountrySelectionGeneratorInput(),success:function(a){b(C).html(a);j(f.getLocationData())}})}function z(a){f.changeLocation(a.data,null,function(){m(f.getLocationData())})}function s(a){f.changeLocation(g.mapCodeToLocationData(a.value),null,function(){j(f.getLocationData())})}function t(){var a=b(w).val();g.validateZipCode(a)?f.changeLocation({zipCode:g.preprocessZipCode(a),locationType:f.locationTypes.locationInput},function(){e(A)},function(){e(J)}):g.isMilitaryZipCode(a)?e(K):e(J)}
function r(){i.when(d.addressSelectorComponentType).execute(function(a){a.get(d.addressSelectorComponentName)&&a.get(d.addressSelectorComponentName).hide()})}function p(){var c=b(D+" .a-radio"),e=b(D+" .a-radio.aok-hidden"),c=c.length===e.length;e.slice(0,c?d.initialAddressLoadCount:d.addressReloadCount).removeClass("aok-hidden");b(D+" .a-radio.aok-hidden").length===0&&(b(H).addClass("aok-hidden"),b(N).addClass("aok-hidden"));c||a.logEvent(a.getEvents().click.seeMore)}function u(a){n(a);m(a);l(a);
j(a);r()}function x(){var d=f.getLocationData();l(d);h.isRecognizedCustomer&&b(D+" .a-radio").length===0&&b(v).length===0&&c.get(B,{params:{currentAddressId:d.addressId,deviceType:h.deviceType},success:function(a){a&&(b("#unifiedLocationTitleNoAddress").remove(),b("#unifiedLocationAccountAddrList").remove(),b("#unifiedLocationSeeMoreDiv").remove(),b("#unifiedLocationTitleSelectAddress").remove(),b(E).before(a),p())}});b.trim(b(C).html()).length||F(d);a.logWidgetView(a.getEvents().view.addressSelector)}
var B="/gp/delivery/ajax/get-address-selections.html",P="/gp/delivery/ajax/get-country-selections.html",O=".lux-location-label",D="#LUXAddressSelections",v="#LUXNoAddressNote",E=".lux-address-selector-divider",H="#LUXSeeMoreAddressLink",N="#LUXAddressActionSeparator",C="#unifiedLocationCountrySelectionDiv",w="#unifiedLocationAddrInput",o="#LUXInvalidZipCodeAlert",q="#LUXMilitaryZipCodeAlert",y="data-lux-address-selection",J=1,K=2,A=3;return{activate:function(){var g=f.getLocationData();a.logPageView(g.locationType);
g.locationType===f.locationTypes.region&&n(g);c.on("a:popover:beforeShow:"+d.addressSelectorComponentName,x);l(g);c.on(f.locationChangeEventName,u);c.declarative("lux-address-selection",["change"],z);b(document).delegate(w,"keypress",function(a){a.which===13&&t()});b(document).delegate(w,"focus",function(){e(A)});b(document).delegate("#unifiedLocationAddrUpdate","click",t);b(document).delegate("#unifiedLocationSignIn","click",function(){a.logEvent(a.getEvents().click.signIn);k.location.href=d.signInURL+
k.location.pathname});b(document).delegate(H,"click",p);b(document).delegate(".lux-manage-address-link","click",function(){a.logEvent(a.getEvents().click.manageAddressBook);return!0});c.on("a:dropdown:"+d.countrySelectorComponentName+":select",s)},refresh:function(){u(f.getLocationData())}}});i.declare("LUXWidgetConfig",{addressSelectorComponentName:"LUXAddressSelector",addressSelectorComponentType:"a-popover",countrySelectorComponentName:"LUXCountrySelector",countrySelectorComponentType:"a-dropdown",
initialAddressLoadCount:5,addressReloadCount:5,signInURL:"/gp/sign-in.html?ie=UTF8&useRedirectOnSuccess=1&path="});i.when("A","jQuery","LUXController","RegionNames","ready").register("LUXRegionData",function(c,b,h,d){function g(a){if(c.objectIsEmpty(a)||!a.countryCode||!a.zipCode)return null;for(var b in f)if(f.hasOwnProperty(b)&&c.reduce(f[b],function(d,g,h){return d&&!c.objectIsEmpty(a[h])&&c.equals(a[h],f[b][h])},!0))return b;return null}var f={"GB-ML":{countryCode:"GB",zipCode:"KA10 6EB"},"GB-NI":{countryCode:"GB",
zipCode:"BT1 3ES"},"GB-JE":{countryCode:"GB",zipCode:"JE2 4QA"},"GB-IS":{countryCode:"GB",zipCode:"ZE1 0BX"},"GB-BF":{countryCode:"GB",zipCode:"BFPO 204"},"GB-HI":{countryCode:"GB",zipCode:"PH41 4PU"},"DE-ML":{countryCode:"DE",zipCode:"60313"},"DE-GI":{countryCode:"DE",zipCode:"27498"},"FR-ML":{countryCode:"FR",zipCode:"75001"},"FR-CH":{countryCode:"FR",zipCode:"20000"},"FR-GP":{countryCode:"FR",zipCode:"97100"},"FR-GY":{countryCode:"FR",zipCode:"97300"},"FR-MC":{countryCode:"FR",zipCode:"98000"},
"FR-MQ":{countryCode:"FR",zipCode:"97200"},"FR-NC":{countryCode:"FR",zipCode:"98800"},"FR-PF":{countryCode:"FR",zipCode:"98700"},"FR-RE":{countryCode:"FR",zipCode:"97400"},"FR-SB":{countryCode:"FR",zipCode:"97133"},"FR-SM":{countryCode:"FR",zipCode:"97150"},"FR-SP":{countryCode:"FR",zipCode:"97500"},"FR-WF":{countryCode:"FR",zipCode:"98611"},"FR-YT":{countryCode:"FR",zipCode:"97600"},"IT-ML":{countryCode:"IT",zipCode:"20125"},"IT-II":{countryCode:"IT",zipCode:"09121"},"ES-ML":{countryCode:"ES",zipCode:"28004"},
"ES-BI":{countryCode:"ES",zipCode:"07003"},"ES-CI":{countryCode:"ES",zipCode:"35005"},"BR-SP":{countryCode:"BR",zipCode:"01319900",state:"São Paulo",city:"Bela Vista"}};return{getRegions:function(){return f},mapLocationDataToRegionCode:function(a){return g(a)},mapRegionCodeToLocationData:function(a){a=f.hasOwnProperty(a)?b.extend({},{addressLabel:d[a],countryCode:f[a].countryCode,zipCode:f[a].zipCode,state:f[a].state,city:f[a].city,locationType:h.locationTypes.region}):null;return a}}});i.when("A",
"jQuery","ready").register("LUXRegionConfig",function(){var c="AE,AR,AT,AU,BE,BG,BH,BM,BR,CA,CH,CL,CN,CO,CR,CY,CZ,DE,DK,EC,EE,EG,ES,FI,FR,GB,GP,GR,HK,HU,ID,IE,IL,IN,IS,IT,JO,JP,KE,KR,KW,KZ,LI,LT,LU,LV,MC,MO,MT,MX,MY,NG,NL,NO,NZ,OM,PA,PE,PH,PL,PT,QA,RO,RS,RU,SA,SE,SG,SI,SK,TH,TR,TT,TW,US,UY,VE,ZA".split(","),b=[],h=[],d=[],g=/^\d{5}([ \-]\d{4})?$/,f=/^[ \t]*([AFD](\.?)([ \t]?)P(\.?)([ \t]?)O(\.?)[ \t]*[A-Z]{2}[ \t]*[0-9]{5}([ \-][0-9]{4})?)[ \t]*$/;return{getPrimarySelections:function(){return c.concat(h)},
getSecondarySelections:function(){return b.concat(d)},getZipCodePattern:function(){return g},getMilitaryZipCodePattern:function(){return f},preprocessZipCode:function(a){return a.toUpperCase().trim()}}});i.declare("RegionNames",{"GB-ML":"UK - Mainland","GB-BF":"UK - BFPO","GB-JE":"UK - Channel Islands","GB-IS":"UK - Islands","GB-NI":"UK - Northern Ireland","GB-HI":"UK - Scottish Highlands","DE-ML":"Germany - Mainland","DE-GI":"German Islands","FR-ML":"France - Mainland","FR-CH":"Corsica","FR-GP":"Guadeloupe",
"FR-GY":"Guyane","FR-MC":"Monaco","FR-MQ":"Martinique","FR-NC":"New Caledonia","FR-PF":"French Polynesia","FR-RE":"Reunion","FR-SB":"Saint Barthélemy","FR-SM":"Saint Martin","FR-SP":"Saint Pierre and Miquelon","FR-WF":"Wallis and Futuna Islands","FR-YT":"Mayotte","IT-ML":"Italy - Mainland","IT-II":"Italian Islands","ES-ML":"Spain - Mainland","ES-BI":"Spain - Balearic Islands","ES-CI":"Spain - Canary Islands, Ceuta and Melilla","BR-SP":"Brazil"});i.declare("CountryNames",{AD:"Andorra",AE:"United Arab Emirates",
AF:"Afghanistan",AG:"Antigua and Barbuda",AI:"Anguilla",AL:"Albania",AM:"Armenia",AN:"Netherlands Antilles",AO:"Angola",AQ:"Antarctica",AR:"Argentina",AS:"American Samoa",AT:"Austria",AU:"Australia",AW:"Aruba",AX:"Aland Islands",AZ:"Azerbaijan",BA:"Bosnia and Herzegovina",BB:"Barbados",BD:"Bangladesh",BE:"Belgium",BF:"Burkina Faso",BG:"Bulgaria",BH:"Bahrain",BI:"Burundi",BJ:"Benin",BL:"Saint Barthelemy",BM:"Bermuda",BN:"Brunei Darussalam",BO:"Bolivia",BQ:"Bonaire, Saint Eustatius and Saba",BR:"Brazil",
BS:"Bahamas, The",BT:"Bhutan",BV:"Bouvet Island",BW:"Botswana",BY:"Belarus",BZ:"Belize",CA:"Canada",CC:"Cocos (Keeling) Islands",CD:"Congo, The Democratic Republic of the",CF:"Central African Republic",CG:"Congo",CH:"Switzerland",CI:"Cote D'ivoire",CK:"Cook Islands",CL:"Chile",CM:"Cameroon",CN:"China",CO:"Colombia",CR:"Costa Rica",CS:"Serbia and Montenegro",CU:"Cuba",CV:"Cape Verde",CW:"Curaçao",CX:"Christmas Island",CY:"Cyprus",CZ:"Czech Republic",DE:"Germany",DJ:"Djibouti",DK:"Denmark",DM:"Dominica",
DO:"Dominican Republic",DZ:"Algeria",EC:"Ecuador",EE:"Estonia",EG:"Egypt",EH:"Western Sahara",ER:"Eritrea",ES:"Spain",ET:"Ethiopia",FI:"Finland",FJ:"Fiji",FK:"Falkland Islands (Malvinas)",FM:"Micronesia, Federated States of",FO:"Faroe Islands",FR:"France",GA:"Gabon",GB:"United Kingdom",GD:"Grenada",GE:"Georgia",GF:"French Guiana",GG:"Guernsey",GH:"Ghana",GI:"Gibraltar",GL:"Greenland",GM:"Gambia, The",GN:"Guinea",GP:"Guadeloupe",GQ:"Equatorial Guinea",GR:"Greece",GS:"South Georgia and the South Sandwich Islands",
GT:"Guatemala",GU:"Guam",GW:"Guinea-Bissau",GY:"Guyana",HK:"Hong Kong",HM:"Heard Island and the McDonald Islands",HN:"Honduras",HR:"Croatia",HT:"Haiti",HU:"Hungary",ID:"Indonesia",IE:"Ireland",IL:"Israel",IM:"Isle of Man",IN:"India",IO:"British Indian Ocean Territory",IQ:"Iraq",IR:"Iran, Islamic Republic of",IS:"Iceland",IT:"Italy",JE:"Jersey",JM:"Jamaica",JO:"Jordan",JP:"Japan",KE:"Kenya",KG:"Kyrgyzstan",KH:"Cambodia",KI:"Kiribati",KM:"Comoros",KN:"Saint Kitts and Nevis",KP:"Korea, Democratic People's Republic of",
KR:"Korea, Republic of",KW:"Kuwait",KY:"Cayman Islands",KZ:"Kazakhstan",LA:"Lao People's Democratic Republic",LB:"Lebanon",LC:"Saint Lucia",LI:"Liechtenstein",LK:"Sri Lanka",LR:"Liberia",LS:"Lesotho",LT:"Lithuania",LU:"Luxembourg",LV:"Latvia",LY:"Libya",MA:"Morocco",MC:"Monaco",MD:"Moldova, Republic of",ME:"Montenegro",MF:"Saint Martin",MG:"Madagascar",MH:"Marshall Islands",MK:"Macedonia, The Former Yugoslav Republic of",ML:"Mali",MM:"Myanmar",MN:"Mongolia",MO:"Macao",MP:"Northern Mariana Islands",
MQ:"Martinique",MR:"Mauritania",MS:"Montserrat",MT:"Malta",MU:"Mauritius",MV:"Maldives",MW:"Malawi",MX:"Mexico",MY:"Malaysia",MZ:"Mozambique",NA:"Namibia",NC:"New Caledonia",NE:"Niger",NF:"Norfolk Island",NG:"Nigeria",NI:"Nicaragua",NL:"Netherlands",NO:"Norway",NP:"Nepal",NR:"Nauru",NU:"Niue",NZ:"New Zealand",OM:"Oman",PA:"Panama",PE:"Peru",PF:"French Polynesia",PG:"Papua New Guinea",PH:"Philippines",PK:"Pakistan",PL:"Poland",PM:"Saint Pierre and Miquelon",PN:"Pitcairn",PR:"Puerto Rico",PS:"Palestinian Territories",
PT:"Portugal",PW:"Palau",PY:"Paraguay",QA:"Qatar",RE:"Reunion",RO:"Romania",RS:"Serbia",RU:"Russian Federation",RW:"Rwanda",SA:"Saudi Arabia",SB:"Solomon Islands",SC:"Seychelles",SD:"Sudan",SE:"Sweden",SG:"Singapore",SH:"Saint Helena, Ascension and Tristan da Cunha",SI:"Slovenia",SJ:"Svalbard and Jan Mayen",SK:"Slovakia",SL:"Sierra Leone",SM:"San Marino",SN:"Senegal",SO:"Somalia",SR:"Suriname",SS:"South Sudan",ST:"Sao Tome and Principe",SV:"El Salvador",SX:"Sint Maarten",SY:"Syria",SZ:"Swaziland",
TC:"Turks and Caicos Islands",TD:"Chad",TF:"French Southern Territories",TG:"Togo",TH:"Thailand",TJ:"Tajikistan",TK:"Tokelau",TL:"Timor-leste",TM:"Turkmenistan",TN:"Tunisia",TO:"Tonga",TR:"Turkey",TT:"Trinidad and Tobago",TV:"Tuvalu",TW:"Taiwan",TZ:"Tanzania, United Republic of",UA:"Ukraine",UG:"Uganda",UM:"United States Minor Outlying Islands",US:"United States",UY:"Uruguay",UZ:"Uzbekistan",VA:"Holy See",VC:"Saint Vincent and the Grenadines",VE:"Venezuela",VG:"Virgin Islands, British",VI:"Virgin Islands, U.S.",
VN:"Vietnam",VU:"Vanuatu",WF:"Wallis and Futuna",WS:"Samoa",XK:"Kosovo",YE:"Yemen",YT:"Mayotte",YU:"Yugoslavia",ZA:"South Africa",ZM:"Zambia",ZW:"Zimbabwe"});i.when("A","jQuery","LUXController","LUXRegionData","LUXRegionConfig","LUXContext","CountryNames","RegionNames").register("LUXUtils",function(c,b,h,d,g,f,a,e){function i(b){return!c.objectIsEmpty(b)&&b.countryCode&&a.hasOwnProperty(b.countryCode)?c.equals(b.locationType,h.locationTypes.country)?b.countryCode:c.equals(b.locationType,h.locationTypes.region)?
d.mapLocationDataToRegionCode(b):d.mapLocationDataToRegionCode(b)||b.countryCode:null}function k(b){return a.hasOwnProperty(b)?a[b]:e.hasOwnProperty(b)?e[b]:null}function l(a){var b={};if(!c.objectIsEmpty(a))for(var d=a.length,e=0;e<d;e++)b[k(a[e])]=a[e];return b}return{getNameForCode:function(a){return k(a)},mapCodeToLocationData:function(b){b=b?a.hasOwnProperty(b)?{countryCode:b,locationType:h.locationTypes.country}:d.mapRegionCodeToLocationData(b):null;return b},mapLocationDataToCode:function(a){return i(a)},
generateLocationLabel:function(a){var b="";return b=a.addressLabel?a.addressLabel:a.locationType!==h.locationTypes.region&&a.locationType!==h.locationTypes.country&&(a.city||a.state)&&a.zipCode?(a.city?a.city+", ":"")+(a.state?a.state+" ":"")+a.zipCode:k(i(a))},prepareCountrySelectionGeneratorInput:function(){return{deviceType:f.deviceType,primarySelections:JSON.stringify(l(g.getPrimarySelections())),secondarySelections:JSON.stringify(l(g.getSecondarySelections()))}},validateZipCode:function(a){return!c.objectIsEmpty(a)&&
g.getZipCodePattern().test(a.toUpperCase())},preprocessZipCode:function(a){return g.preprocessZipCode(a)},isMilitaryZipCode:function(a){return!c.objectIsEmpty(a)&&g.getMilitaryZipCodePattern().test(a.toUpperCase())}}});i.when("A","jQuery","LUXContext","ready").register("LUXMetrics",function(c,b,h){function d(b,c){k.ueLogError&&b&&k.ueLogError({message:b},{logLevel:c||"ERROR",attribution:a})}function g(a){k.ue?k.ue.count(a,(k.ue.count(a)||0)+1):d("Failed to increment metrics counter: "+a+" because window.ue is not present.",
"ERROR")}function f(){var a;if(a=k.ue_pty)a:{a=k.ue_pty;for(var b in e)if(e.hasOwnProperty(b)&&c.indexOfArray(e[b],a)!==-1){a=!0;break a}a=!1}return a?k.ue_pty:"unrecognizedPage"}var a="LocationUX",e={detail:["Detail","DetailAW","DetailWebView","TabletUDP"],search:["Search","SearchAW"],offerListing:["OfferListing","OfferListingAW","OfferListingMobileAppAW"]},n={click:{signIn:"click.signIn",seeMore:"click.seeMore",manageAddressBook:"click.manageAddressBook"},view:{page:"view.page",addressSelector:"view.addressSelector",
countrySelector:"view.countrySelector"},selection:"selection",override:"override"};return{getPageType:function(){return f()},getEvents:function(){return n},logLocationChange:function(b){i.when("LUXController").execute(function(d){var i=f(),k=a+"."+i;k+=c.equals(b,d.locationTypes.locationInput)||c.equals(b,d.locationTypes.realmDefault)||c.equals(b,d.locationTypes.ip2location)?"."+n.override+"."+b:"."+n.selection+"."+b;!c.equals(b,d.locationTypes.defaultAddress)&&!c.equals(b,d.locationTypes.accountAddress)&&
!c.equals(b,d.locationTypes.lockerAddress)&&(k+="."+(h.isRecognizedCustomer?"recognized":"unrecognized"));c.indexOfArray(e.detail,i)!==-1&&h.isRecognizedCustomer&&(k+="."+(h.isOneClick?"1Click":"Non1Click"));g(k)})},logPageView:function(b){i.when("LUXController").execute(function(d){var i=f(),k=a+"."+i+"."+n.view.page+"."+b;!c.equals(b,d.locationTypes.defaultAddress)&&!c.equals(b,d.locationTypes.accountAddress)&&!c.equals(b,d.locationTypes.lockerAddress)&&(k+="."+(h.isRecognizedCustomer?"recognized":
"unrecognized"));c.indexOfArray(e.detail,i)!==-1&&h.isRecognizedCustomer&&(k+="."+(h.isOneClick?"1Click":"Non1Click"));g(k)})},logWidgetView:function(b){var d=f(),b=a+"."+d+"."+b+"."+(h.isRecognizedCustomer?"recognized":"unrecognized");c.indexOfArray(e.detail,d)!==-1&&h.isRecognizedCustomer&&(b+="."+(h.isOneClick?"1Click":"Non1Click"));g(b)},logEvent:function(b){b=a+"."+f()+"."+b;g(b)},logError:function(a,b){d(a,b)}}})})})(function(){var i=window.AmazonUIPageJS||window.P,k=i._namespace||i.attributeErrors;
return k?k("DeliveryStatic"):i}(),window);
/* ******** */
(function(m){m.execute(function(){m.when("A","a-popover","cf").register("add-to-wish-list",function(c,e){var h,k,r;function n(){d("#wishListDropDown").removeClass("a-button-selected");d("#wishListMainButton").removeClass("a-button-selected")}function i(a){c.state("atwl",d.extend(c.state("atwl")||{},a))}function z(){return(c.state("atwl")||{}).dropDownHtml}function m(){i({dropDownHtml:""})}function t(){var a=d("#atwl-dd-ul").parent();if(a&&a.get(0)){var b=a.get(0).scrollHeight,c=a.height(),a=2*parseInt(a.css("padding-top"),
10);return b>c+a}return!1}function G(){return parseInt(d.browser.version,10)<9&&document.body&&document.body.parentElement?!(!document.body.parentElement.scrollLeft&&!document.body.parentElement.scrollTop):!1}function H(a){a.find(".a-button-close").hide();a.find(".a-popover-content").css({"margin-right":"0px"});a.css({padding:"0"});a.find(".a-popover-inner").css({padding:"0"});setTimeout(function(){a.removeClass("a-arrow-bottom");d("#atwl-rich-content").css({"margin-bottom":"0px",width:"auto"});if(d.browser.msie){var b=
c.state("atwl")||{},g=d("#"+b.wishlistButtonSubmitId),b=g.offset(),A=g.height(),g=b.left,b=b.top+A;G()&&(g+=document.body.parentElement.scrollLeft,b+=document.body.parentElement.scrollTop);t()&&(g-=17);a.css({left:g+"px",top:b+"px"})}},50)}function u(){if(w){var a=e.get(w);a&&a.hide()}}function B(a){d("#"+a).children().first().width(h);u();if(e){var b=e.get(w),g=c.state("atwl")||{},b=b?e.get(w):e.create(d("#add-to-wishlist-button-group"),{content:d("#"+a).html(),name:"atwl",skin:function(a){return a},
activate:"onmouseclick",width:h,position:g.dropDownPosition||"triggerBottom"});b.update({width:h,content:d("#"+a).html()});w=b.id;b.show().updatePosition();H(b.$popover)}}function C(){n();I++;u();B("atwl-dd-error-holder")}function S(){u();var a=c.state("atwl")||{};return I>=a.maxAjaxFailureCount}function J(){var a=c.state("atwl")||{};return e.create(d("#add-to-wishlist-button-group"),{content:z(),name:"atwl",skin:function(a){return a},activate:"onmouseclick",position:a.dropDownPosition||"triggerBottom"})}
function T(a){var b;b=G()?50:0;setTimeout(function(){var b=d("#atwl-popover-inner"),c=b.width();t()?c+=k:d(".atwl-dd-list-name").each(function(){var a=d(this);a.width(a.width()+r)});var f=a.find("ul li a.a-active").first();f.css("margin-left","1px");f.parent().focus();b.width(c)},b)}function U(a){a.update({content:z(),width:"auto"});a.show();H(a.$popover);T(a.$popover)}function K(){var a=e.get("atwl");if(a)if(a.isActive()){a.hide();return}else e.remove(a);else a=J(),e.remove(a);a=J();U(a);c.capabilities.touch&&
setTimeout(function(){var a=d("#wishlistButtonStack"),c=a.clone(),A=a.parent();a.remove();A.append(c)},300)}function x(){var a=e.get("atwl");a&&a.isActive()&&a.hide()}function V(a){n();u();var b;try{b=c.parseJSON(a)}catch(g){C();return}typeof b.html!=="undefined"&&b.css!=="undefined"?(i({dropDownHtml:b.html}),a=b.css,d("body").append(a),K()):C()}function W(a){if(a&&a.promoEnabled){var b=a.html;if(b){var d=e.create(D.parent(),{name:"kbpPromoPopover",content:b,position:"triggerBottom",width:a.width});
d.show().lock();c.delay(function(){var a=(c.state("atwl")||{}).kbpPromo||{};a.mouseOver?a.countDown=!0:(d.unlock().hide(),e.remove(d));c.state("atwl",{kbpPromo:a})},1E4)}}}typeof c.state.parse!=="undefined"&&c.state.parse();var p=c.state("popoverState")||{},E="#"+(p.formId||"addToCart");window.setRegistryId=function(a){var b=d(E);b.find("[name='sourceCustomerOrgListID'],[name='colid'],[name='wlPopCommand']").attr("value",a);b.find("[name='submit.add-to-registry.wishlist'],[name='submit.add-to-wishlist']").eq(0).click();
return!1};var y=[];if(p.showWishListDropDown||p.showBabyRegDropdown||p.isAddToWishListDropDownAuiEnabled||p.showPopover){var d=c.$;if(p.showWishListDropDown||p.showBabyRegDropdown){var v,L=function(){var a=function(a){if(!a.data("wired")){a.data("wired",!0);a[0].name="";if(a.css("cursor")!=="not-allowed"){var b=a.attr("data-type"),c=p.wishlistPopoverWidth;a.amazonPopoverTrigger({ajaxSlideDuration:0,align:"left",cacheable:!0,closeEventInclude:"CLICK_OUTSIDE",destination:"/gp/registry/reglist-popover.html?sprited=0&type="+
b,group:"addToWishlist",loadingContent:"<div style='padding: 4px 28px;'><img src='"+window.AmazonPopoverImages.loadingBar+"'/></div>",location:"bottom",locationElement:"#"+a[0].id,locationOffset:[0,-5],showOnHover:!1,skin:"<div id='wishlist-dropdown-content'><div class='ap_content'></div></div>",width:c,onFilled:function(a){d(document).click();a.width(c);window.wlPop&&setTimeout(function(){window.wlPop.onFill(a);a.width(c)},0)}})}v&&(clearInterval(v),v=void 0)}},b="#"+p.babyRegistryId;if(!p.isAddToWishListDropDownAuiEnabled){var g=
c.state("atwl")||{};b+=", #"+g.wishlistButtonId}d(b).each(function(){a(d(this))})};L();var s=function(){v&&clearInterval(v);v=setInterval(L,200)};d("#twister").change(s);c.declarative("swatchthumb-action","click",s)}if(p.isAddToWishListDropDownAuiEnabled){var w,I=0,s=c.state("atwl")||{},M=s.wireDeclaratives,N=d("#"+s.wishlistButtonId);N.addClass("a-declarative");N.attr("data-action","atwl-splitbutton-arrow");var D=d("#"+s.wishlistButtonSubmitId);D.addClass("a-declarative");D.attr("data-action","atwl-splitbutton-main");
d("#wishListMainButton").addClass("a-declarative").attr("data-action","add-wishlist-declarative");h=230;k=10;r=10;i({resetDropDownHtml:m});M||(c.declarative("atwl-splitbutton-arrow","click",function(a){a.$event.preventDefault();setTimeout(function(){n()},0);if(a.$target.css("cursor")==="not-allowed")return!1;if(S())return u(),u(),B("atwl-dd-unavail-holder"),!1;var b=z(),a=c.state("atwl")||{};if(!b||!b.length){B("atwl-dd-spinner-holder");var b=c.state("wishlistDPState")||{},g="website.wishlist.detail.add";
if(typeof b.vendorId!=="undefined")g=b.vendorId;a={url:"/gp/registry/atwl/popover.html?"+d.param({sortMethod:a.sortMethod||0,type:"wishlist",useAll:a.showAllTypes||0,sourceVendorId:g}),cache:!1,success:V,error:C};d.ajax(a)}else K();return!1}),c.declarative("atwl-dd","click",function(a){a.$event.preventDefault();var b=a.data,a=b.id,b=b.type;typeof b==="undefined"&&(b="wishlist");var c="pop_"+a+"_"+b,e=d(E+",#addToWL");e.find("[name='sourceCustomerOrgListID'],[name='colid'],[name='wlPopCommand']").attr("value",
c);e.find("[name='registryID']").attr("value",a);e.find("[name='registryType']").attr("value",b);i({inSubmit:!0});e.find("[name='submit.add-to-registry.wishlist'],[name='submit.add-to-wishlist']").eq(0).click();x();return!1}),c.declarative("atwl-kbp-landing","click",function(a){var b=a.data,a=d(E).find("#ASIN").val(),b=b.url;b+="&asin="+a;window.open(b);return!1}));if((s=c.state("atwl")||{})&&s.sortMethod==="kbp")c.state("atwl",{kbpPromo:{mouseOver:!1,countDown:!1}}),c.ajax("/gp/toys/birthday/atwl-dpx.html",
{method:"get",cache:!1,params:{isAUI:1},success:W,error:function(){}}),M||(c.declarative("atwl-kbp-promo-mouseover","mouseleave",function(){var a=(c.state("atwl")||{}).kbpPromo;a.mouseOver=!1;if(a.countDown){var b=e.get("kbpPromoPopover");b&&(b.unlock().hide(),e.remove(b))}c.state("atwl",{kbpPromo:a})}),c.declarative("atwl-kbp-promo-mouseover","mouseenter",function(){var a=(c.state("atwl")||{}).kbpPromo;a.mouseOver=!0;c.state("atwl",{kbpPromo:a})}),c.on("a:popover:hide:kbpPromoPopover",function(){var a=
e.get("kbpPromoPopover");a.unlock().hide();e.remove(a)}));i({wireDeclaratives:!0})}if(p.showPopover){var O=function(a,b){var d=document.getElementById(p.formId||"addToCart");if(typeof d==="undefined"||d===null)d=document.getElementById("addToWL");var e=[];if(typeof d!=="undefined"&&d!==null){var e=[],f=!1,l=d.elements;l||(l=d.querySelectorAll("input"),f=!0);for(var o=0;o<l.length;o++){var q;if(!(q=f)){q=l[o];var h=/^(?:checkbox|radio)$/i,i=/^(?:submit|button|image|reset|file)$/i,r=/^(?:input|select|textarea|keygen)/i;
if(q){var k=q.type;q=q.name&&!q.disabled&&r.test(q.nodeName)&&!i.test(k)&&(q.checked||!h.test(k))}else q=!1}q&&e.push(l[o])}}f={};l=c.state("wishlistDPState")||{};if(typeof l.asin!=="undefined"&&l.asin!==null)f.asin=l.asin;for(o=0;o<e.length;o++)if(e[o].type!=="submit")f[e[o].name]=e[o].value;f.requestedQty=f.quantity=d!==null&&typeof d.quantity!=="undefined"?d.quantity.value:1;f.sid=typeof f["session-id"]!=="undefined"?f["session-id"]:l.sid;f.cache=!1;f.url=l[a+"Url"];f.action=a;f.type=f.registryType||
"wishlist";if(a==="add")f.type=f.registryType||b,f.caller="aui",f.streaming=l.streaming,f.sourceVendorId=typeof l.vendorId!=="undefined"?l.vendorId:"website.wishlist.detail.add";else if(a==="create")f.create_sid=f.sid,f.create_type=f.registryType||b,f.create_nextAction="add",f.create_includeEmptyList=1,f.create_isFirst=l.isFirstCreate?1:0,f.caller="aui",f.create_sourceVendorId=typeof l.vendorId!=="undefined"?l.vendorId:"website.wishlist.detail.add";return f},F=function(a){var b=a.attr("name"),a=a.parents("form"),
b=d('<input type="hidden" />').attr("name",b).val("1");a.append(d(b));a.submit()},Q=function(){var a=d("#add-wishlist-declarative").closest(".a-button").find("input");F(a)};c.capabilities.touch||d("#add-to-wishlist-button-submit").unbind("click").bind("click",function(a){a.preventDefault();if(d(this).css("cursor")==="not-allowed")return!1;var b="",b=c.state("wishlistDPState")||{},g=d("[name='wlPopCommand']").val(),a=window.currentType;if(g&&g!==""){g=g.split("_");a=g[2];if(a!=="wishlist"&&a!=="giftlist"&&
a!=="supplylist"||d("html").hasClass("a-lt-ie9")){Q();return}b=g[1]==="new"?"create":g[1]==="default"&&b.isFirstCreate?"create":"add"}else if(a="wishlist",b=b.isFirstCreate?"create":"add",b==="add"&&d("html").hasClass("a-lt-ie9")){Q();return}c.state("wishlistDPState",{action:b,type:a});window.currentType=a;d("#add-wishlist-declarative").trigger("click")});var R=function(){for(var a=["wlPopCommand","sourceCustomerOrgListID"],b=0;b<a.length;b++){var c=d('[name^="'+a[b]+'"]');c&&c.length&&c.val("")}};
(c.state("wishlistDPState")||{}).eventsBound||(c.on("a:popover:show:addCreateToWishlist",function(a){var b=a.popover,a=b.$popover,e=c.state("wishlistDPState")||{},h=e.action;a.addClass("pop-huc-"+h);var f=b.$trigger.closest(".a-button").find("input"),a=e.type;f.closest(".a-button-selected").removeClass("a-button-selected");var a=O(h,a),e=a.url,l=a.streaming,o="ajax_"+l,q=new Date;window.ue&&window.uet("tc",o);var i=function(){b.hide();F(f)},r=function(){b.$popover.find("#popover-spinner").addClass("a-hidden");
R()},k=function(){window.ue&&(window.uet("be",o),window.uex("ld",o))},n=function(a,b,c){window.ue&&(window.ues("id",o,a),window.ues("t0",o,b),window.ues("ctb",o,c))};if(h==="create"||!l)c.ajax(e,{method:"post",params:a,success:function(a){a&&a.html?(n(a.requestId,q,"1"),a.status&&a.status==="no-asins"?i():(r(),h==="add"?b.$popover.find("#WLHUC_result").html(a.html).removeClass("a-hidden"):(b.$popover.find("#WLNEW_main").html(a.html).removeClass("a-hidden"),(a=c.state("atwl")||{})&&a.resetDropDownHtml&&
a.resetDropDownHtml()),b.updatePosition()),k()):(h==="create"&&F(f),b.hide())},error:i});else{var j=new XMLHttpRequest;j.open("GET",a.url+"&"+c.$.param(a),!0);j.send(null);var p=0;j.ontimeout=i;j.onerror=i;j.onreadystatechange=function(){try{if(j.readyState>2&&typeof j.status!=="unknown"&&j.status===200&&(typeof j.response!=="undefined"||typeof j.responseText!=="unknown"&&typeof j.responseText!=="undefined")){var a=[];typeof j.response!=="undefined"&&j.response!==null?a=j.response.split(",,,"):typeof j.responseText!==
"unknown"&&typeof j.responseText!=="undefined"&&j.responseText!==null&&(a=j.responseText.split(",,,"));for(var f=p;f<a.length;f++){var e=a[f],g;try{g=c.parseJSON(e)}catch(h){p=f;break}f===0&&g&&g.name==="skeleton"?g&&g.html&&(n(g.requestId,new Date,"1"),g.status&&g.status==="no-asins"?i():(r(),b.$popover.find("#WLHUC_result").html(g.html).removeClass("a-hidden"))):g&&g.name&&g.html&&g.name==="pcomp"?d("#wishListMainButton").hasClass("a-hidden")||(d("#wishListMainButton,#add-to-wishlist-button-group").addClass("a-hidden"),
x(),d("#wishlistButtonStack").append(g.html)):g&&g.name&&g.html&&g.name!=="js"?(b.$popover.find("#"+g.name).html(g.html),f===1&&window.ue&&window.uet("cf",o)):g&&g.html&&b.$popover.find("#WLHUC_result").append(g.html);b.updatePosition()}j.readyState===4&&k()}else typeof j.status!=="unknown"&&j.status!==200&&i()}catch(q){i()}}}}),c.on("a:popover:beforeShow:addCreateToWishlist",function(a){var a=a.popover,b=c.state("wishlistDPState")||{};a.$popover.find("#popover-spinner").css({margin:"10% 40%"});a.$popover.find("#popover-spinner").removeClass("a-hidden");
a.$popover.find(".wlAddCreatePop").html("").addClass("a-hidden");var d=b.action;a.update({width:b[d+"Width"],header:b[d+"Header"],height:b[d+"Height"]});a.updatePosition()}),c.on("a:popover:hide:addCreateToWishlist",function(){d(".a-modal-scroller").css({visibility:"hidden"});R()}),c.state("wishlistDPState",{eventsBound:!0}),c.declarative("add-wishlist-declarative",["click"],function(){var a=c.state("wishlistDPState")||{},b=O(a.action,a.type),g=function(){d("#wishListMainButton,#add-to-wishlist-button-group").addClass("a-hidden");
x();d("#atwl-error-holder").removeClass("a-hidden")};d("#atwl-dd-no-title-holder").hasClass("a-hidden")||d("#atwl-dd-no-title-holder").addClass("a-hidden");var e=function(a){try{if(typeof a!=="undefined"){var b="";if(typeof a.pcompHtml!=="undefined"&&a.pcompHtml.trim()!=="")b=a.pcompHtml;else{g();return}d("#wishListMainButton").hasClass("a-hidden")||(d("#wishListMainButton,#add-to-wishlist-button-group").addClass("a-hidden"),x(),d("#atwl-output-holder").empty(),d("#atwl-output-holder").append(b),
d("#atwl-output-holder").removeClass("a-hidden"))}else g();for(b=0;b<y.length;b++)if(typeof y[b]==="function")y[b](a)}catch(c){g()}},f=function(a){var b=document.createElement("input");b.type="hidden";b.id=a;b.name=a;typeof d("#addItemForm")!=="undefined"&&d("#addItemForm").append(b);return b};if((typeof b.asin==="undefined"||b.asin.length===0)&&(typeof b.name==="undefined"||b.name.length===0))d("#atwl-dd-no-title-holder").removeClass("a-hidden");else if(a.custRecognized==="false"){if(a.asin===null){var a=
f("name.0"),b=f("imageUrl.0"),e=f("productUrl.0"),i=f("priceInput"),f=f("quantity.0");a.value=document.getElementById("name").value;b.value=document.getElementById("imageUrl").value;e.value=document.getElementById("productUrl").value;i.value=document.getElementById("price").value;f.value=1}d("#addItemForm").submit()}else c.ajax(b.url,{method:"get",dataType:"json",cache:!1,params:b,success:e,error:g})}))}}return{setPostAddSuccess:function(a){y.push(a)}}});m.when("A","a-modal","ready").execute(function(c,
e){var h=c.$,k=c.state("jumpstart-success-modal-state");k!==void 0&&!k.showDPHeadJavaScript&&k.showBabyRegSuccessModal&&k.hasBabyReg&&h(document).delegate("#add-to-registry-baby-button-submit","click",function(c){c.preventDefault();c=h("#is-fully-selected-baby-reg").val()==="true";if(typeof c!=="undefined"&&c!==null&&c){var c=h("#ASIN").val(),n=h("#rsid").val(),c={name:"baby-registry-add-success-modal",header:k.addSuccessModalHeader,url:"/gp/baby-reg/utils/RAW/raw-request.html/ref=br_js_asm?update=addSuccess&asin="+
c+"&sid="+n},n=h("#add-to-registry-baby-button-submit");e.create(n,c);e.get(h("#add-to-registry-baby-button-submit")).show()}})});m.when("A","b2b-lists-detail").execute(function(c,e){function h(){var e=c.$(k),h=c.$(r),m=c.$(n),t=1;e&&e.is(":visible")?t=e.val():h&&h.is(":visible")?t=h.val():m&&m.is(":visible")&&(t=m.val());return t}if(e.isEnabled()){var k="#free-form-quantity-dropdown",r="#quantity-update-text",n="#quantity";c.on("a:popover:beforeShow:add-to-business-list-modal",function(i){var k=
c.$("#ASIN").val();e.updateModal(i.popover,h(),k)})}});m.when("A","ready").register("b2b-lists-detail",function(c){function e(c,e,m){var n=RegExp("([?&])"+e+"=.*?(&|$)","i"),i=c;c.match(n)&&(i=c.replace(n,"$1"+e+"="+m+"$2"));return i}return{updateModal:function(h,k,m){var n=(c.state("businessListPageState")||{}).businessListUrl,i="";n&&(i=e(n,"quantity",k),i=e(i,"asin",m));h.update({url:i})},isEnabled:function(){return c.$("#add-business-list-button").length>0?!0:!1}}})})})(function(){var m=window.AmazonUIPageJS||
P,c=m.attributeErrors;return c?c("RegistryDPAssets"):m}());
/* ******** */
(function(g){g.execute(function(){g.when("A","a-carousel-framework","a-carousel-ajax-standard").register("AmazonClicks",function(a,k,m){var o=a.extend([],m);o.getItems=function(a,f,b){var d=a.getAttr("pageNumber");a.getAttr("pageSize");var i=a.getAttr("fetchedItems"),g=JSON.parse("["+a.getAttr("initialSeenAsins")+"]"),c="[",h;for(h=0;h<g.length;h++)c+='"'+g[h]+'",';c=c.substring(0,c.length-1);for(h=0;h<i.length;h++)typeof i[h]==="object"&&c.indexOf(i[h].oid)===-1&&(c+=',"'+i[h].oid+'"');c+="]";b.pg=
d;b.tot=a.getAttr("set_size");b.start=b.offset;b.num=b.count;b.cc=d===1?0:b.offset;b.oData=c;m.getItems(a,f,b)};k.registerStrategy("ajax","clicksCustomAjax",o);return{registerCustomAjax:function(e,f,b){f=a.extend([],m);f.getItems=function(a,d,c){var e=a.getAttr("pageNumber");a.getAttr("pageSize");var f=a.getAttr("fetchedItems"),g="[",j;for(j=0;j<b.length;j++)g+='"'+b[j]+'",';g=g.substring(0,g.length-1);for(j=0;j<f.length;j++)typeof f[j]==="object"&&g.indexOf(f[j].oid)===-1&&(g+=',"'+f[j].oid+'"');
g+="]";c.pg=e;c.tot=a.getAttr("set_size");c.start=c.offset;c.num=c.count;c.cc=e===1?0:c.offset;c.oData=g;m.getItems(a,d,c)};var e=k.getCarouselByName(e+"_carousel"),d=e.getAttr("ajax");d.prefetch_next_page=!1;e.setAttr("circular",!1);e.setAttr("ajax",d);e.strategies.ajax=f},registerFeedbackEvents:function(e,f,b,d,g){var k=!0,c=function(){a.$("#"+f).text(d);k=!1;a.$("."+g).each(function(){a.$(this).show()})},h=function(){a.$("#"+f).text(b);k=!0;a.$("."+g).each(function(){a.$(this).hide()})};a.$("#"+
f).click(function(){k?c():h()});a.on("a:carousel:"+e+":change:pageNumber",h);h()},lazyLoadCarousel:function(e,f,b){var d=a.$("#"+e),i=function(){g.when("A","a-carousel-framework").execute(function(a,c){if(a.onScreen(d,800)){var e=d.width(),g=d.offset().top;a.off("scroll",i);a.get(f+"&bWidth="+e+"&yPos="+g.toFixed(0),{success:function(a){c.onInit(b,function(){var b=d.find(".a-carousel-container");b!==void 0&&c.kill(b);d.html(a)});c.createAll()},error:function(){c.onInit(b,function(){d.html("")})}})}})};
a.on("scroll",i);i()},truncateTitles:function(e){a.$("."+e).each(function(){var f=a.$(this);if(f.css("overflow")==="hidden"){var b=f.html(),d=a.$(this.cloneNode(!0)).hide().css("position","absolute").css("overflow","visible").width(f.width()).height("auto");f.after(d);for(d.html(b);b.length>0&&d.height()>f.height();)b=b.substr(0,b.length-1),d.html(b+"&#133;");f.html(d.html()).height("auto").removeClass(e);d.remove()}})}}})})})(function(){var g=window.AmazonUIPageJS||P,a=g.attributeErrors;return a?
a("ProductAdsDetailPageAssets"):g}());
/* ******** */
(function(d){d.execute(function(){d.when("A","a-button","a-modal").register("tradein-self-grading",function(d,c,a){function b(a){return d.reduce(t,function(b,c,e){b[e]=d.reduce(a,function(a,b){return Math.abs(t[a]-c)>=Math.abs(t[b]-c)&&t[b]>=c?b:a},"Unacceptable");return b},{})}function i(){return a.get(n(".tradein-grading-header").closest(".a-popover-modal"))}function j(a){var b=function(a,b){if(b==="Unacceptable")return g(a,!1),!0;g(a,!0);var c=u[a][b];e(a+"-condition",b);var d=n("#"+q+"-graded-"+
a+"-price"),f=d.html().replace(/[0-9.,]/g,"").trim(),c=Number(c).toFixed(2);d.html(f+c);return!1},c=y[a],a=z[a],f=parseFloat(u.trade[c]);d.trigger("set-tradein-condition-tiv",c,f);c=b("trade",c);b=b("sell",a);return c&&b}function e(a,b){n('input[name="'+a+'"]',n("#tradein-grading-form")).val(b)}function f(a){r!==a&&(r&&n(".tradein-sell-type-"+r).removeClass("tradein-active"),n(".tradein-sell-type-"+a).addClass("tradein-active"),r=a,e("sell-type",r),n("input",n("#sell_type_"+a)).click(),h("sell_type",
!0))}function k(a,b,d){b?(n(".tradein-grade-button").removeClass("shorted"),c(".tradein-grade-button").enable(),n(".tradein-question-text").removeClass("disabled").removeClass("shorted"),n(".tradein-gate").removeClass("disabled")):(n(".tradein-grade-button-"+a).addClass("shorted"),n("#tradein-question-text-"+a).addClass("shorted"),n(".tradein-question-text:not(.shorted)").addClass("disabled"),d==="unacceptable"&&n(".tradein-gate").addClass("disabled"),c(".tradein-grade-button:not(.shorted)").disable())}
function g(a,b){n(".tradein-sell-type-"+a).toggleClass("tradein-hidden",!b);r===a&&h("sell_type",b)}function m(a,b){n("#"+q+"-graded-"+a).toggleClass("tradein-hidden",!b);a==="acceptable"&&h("form_complete",b);i()&&i().updatePosition()}function h(a,b){var c=d.state(x);a in c&&(c[a]=b,d.state(x,c))}function p(a){a=d.reduce(v,function(a,b){return t[b]>t[a]?b:a},a);return j(a)}var n=d.$,v,t,u={},q,r,s,o,y,z,w,x="tradein-grading-gates";return{getQuestionnaire:function(){return v},configureQuestionnaire:function(a){q=
a.asin;t=a.questionnaire.conditions;var c=a.tradein_conditions;c.push("Unacceptable");y=b(c);c=a.sell_conditions;c.push("Unacceptable");z=b(c);o=0;s=a.questionnaire.questions.length;v={};u.trade=a.tradein_offers;u.sell=a.sell_offers;w={Unacceptable:{show:"unacceptable",hide:"acceptable"},New:{show:"acceptable",hide:"unacceptable"},memo:{}};r=null;d.state.replace(x,a.gates);d.trigger("load-saved-tradein-questionnaire-state");f("trade");n(".tradein-grading-header").closest(".a-popover-wrapper").addClass("no-border")},
setQuestionnaire:function(a){v=a},handleAnswer:function(a,b){v[a]||o++;v[a]=b;n("#tradein-question-text-"+a).addClass("a-color-secondary").removeClass("a-color-state");e("question-"+a,b);var c;c=w[b];var d=w.memo;!c&&d[a]?(m(w[d[a]].show,!1),k(a,!0),delete d[a],c=!1):c?(d[a]=b,c.show==="acceptable"&&j(b),m(c.hide,!1),m(c.show,!0),k(a,!1,c.show),c=!0):c=!1;o<s||c||(p(b)?(m("acceptable",!1),m("unacceptable",!0)):(m("acceptable",!0),m("unacceptable",!1)))},setSellType:f,gradeQuestionnaire:p,getContinueButton:function(){return c(".tradein-grade-continue")},
getNextButton:function(){return c("#tradein-grade-next")},gateKey:x,setGate:h}});d.when("A","tradein-self-grading").execute("registering self-grading actions",function(d,c){var a=d.$;d.state.bind(c.gateKey,function(a){var a=d.reduce(a,function(a,b){return a&&b},!0),i=c.getContinueButton(),j=c.getNextButton();a?(i.enable(),j.enable()):(j.disable(),i.disable())});d.declarative("verify-graded-isbn","click",function(b){b=a("#"+b.data.selector);c.setGate("isbn_verify",b.is(":checked"))});d.declarative("tradein-question-answer",
"click",function(a){a=a.data;c.handleAnswer(a.question,a.answer)});d.declarative("choose-graded-item-type","click",function(a){c.setSellType(a.data.sell_type)});d.declarative("add-graded-item","click",function(b){a(":input",b.$currentTarget).is(":disabled")||a("#"+b.data.form_id).submit()});d.on("set-tradein-sellType",function(a){c.setSellType(a)})})})})(function(){var d=window.AmazonUIPageJS||window.P,l=d._namespace||d.attributeErrors;return l?l("TradeInSelfGradingAssets"):d}(),window);
/* ******** */
(function(a){a.execute(function(){})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("DetailPageOffersMulticlickAssets"):a}());(function(a){a.execute(function(){})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("DetailPageDesktopOffersAssets"):a}());
/* ******** */
(function(b){b.execute(function(){b.when("A","ready").execute(function(a){var c=a.state("rentbox-common-page-state");if(c&&c.onlyUnrestrictedOfferAvailable==="false"){var e=c.rentBox;a.$("#dropdownAndPopover").show();a.$("#rentButton").attr("href",c.defaultRentNowUrl);b.when("A","a-popover","ready").execute(function(a,b){var c=a.$,e=c("#rentButton");b.create(c("#rentButton"),{name:"rentButtonHoverPopup",position:"triggerLeft",closeButton:"false",width:"200"});e.attr("title","").css("cursor","not-allowed")});
c.bothOffersAvailable==="true"&&(a.$("#rentPrice").html(e.displayedRentalPrice),c.showPrimeLogo==="true"&&(a.$("#rentPrice").removeClass("offer-price").addClass("rental-offer-price"),a.$("#rentPrice").removeClass("a-size-medium").addClass("a-size-base")),a.$("#rentListPriceSavings").text(e.displayedPriceSavings),a.$("#rentBoxMerchantDetails").hide(),e.showSuperSaverShippingLink===!0?a.$("#rentBoxFreeShippingMsg").show():a.$("#rentBoxFreeShippingMsg").hide(),b.when("A","a-modal").execute(function(a,
b){var e=a.$;b.get(e("#rentalDetailsPopover")).update({url:c.priceDetailsDefaultUrl})}));var f=!1;a.$("#rbbContainer .rbbSection .rbbHeader").click(function(){var d=a.$(this),d=d.hasClass("rbbHeader")?d:d.parents(".rbbHeader");if(d.parents(".rbbSection").hasClass("selected"))return!1;a.$("#rbbContainer").find(".rental-offer-price").removeClass("a-color-price").addClass("a-color-base");d.find(".rental-offer-price").removeClass("a-color-base").addClass("a-color-price");f&&(a.$("#rbbContainer").find(".rental-offer-price").removeClass("a-size-medium").addClass("a-size-base"),
d.find(".rental-offer-price").removeClass("a-size-base").addClass("a-size-medium"))});var i=!a.$.isEmptyObject(e.unrestrictedOffer)&&e.unrestrictedOfferAvailable;if(i)var h=e.greenStates,g=function(){var d=c.unrestrictedOfferDetails;a.$("#rentPrice").html(d.price);c.rentalCartEnabled==="true"?a.$("#rentButton").attr("href",d.addToRentalCartUrl):a.$("#rentButton").attr("href",d.rentNowUrl);a.$("#rentListPriceSavings").text(d.listPrice+" ("+d.listPriceSavings+"%)");a.$("#rentBoxMerchantName").text(d.unrestrictedOfferMerchantName);
a.$("#rentBoxMerchantUrlLink").text(d.merchantName);a.$("#rentBoxMerchantUrlLink").attr("href",d.merchantUrl);e.unrestrictedOffer.superSaverShippingEligible===!0?a.$("#rentBoxFreeShippingMsg").show():a.$("#rentBoxFreeShippingMsg").hide();b.when("A","a-modal").execute(function(a,b){var c=a.$;b.get(c("#rentalDetailsPopover")).update({url:d.popoverJsUrl})})},j=function(){var d=c.restrictedOfferDetails;a.$("#rentPrice").html(d.price);c.rentalCartEnabled==="true"?a.$("#rentButton").attr("href",d.addToRentalCartUrl):
a.$("#rentButton").attr("href",d.rentNowUrl);a.$("#rentListPriceSavings").text(d.listPrice+" ("+d.listPriceSavings+"%)");a.$("#rentBoxMerchantName").text(d.merchantName);a.$("#rentBoxMerchantUrlLink").text(d.merchantName);a.$("#rentBoxMerchantUrlLink").attr("href",d.merchantUrl);e.restrictedOffer.superSaverShippingEligible===!0?a.$("#rentBoxFreeShippingMsg").show():a.$("#rentBoxFreeShippingMsg").hide();b.when("A","a-modal").execute(function(a,b){var c=a.$;b.get(c("#rentalDetailsPopover")).update({url:d.popoverJsUrl})})};
var k=function(){b.when("A","a-popover","ready").execute(function(a,b){var c=a.$,c=c("#rentButton");b.remove(c);c.attr("title","Rent").css("cursor","pointer")});c.rentalCartEnabled==="true"?a.$("#rentButton").attr("href",c.restrictedOfferDetails.addToRentalCartUrl):a.$("#rentButton").attr("href",c.restrictedOfferDetails.rentNowUrl)};a.on("a:dropdown:selected:shippingState",function(c){a.$("#selectShippingState .a-dropdown-label").html("Shipping To:");k();f||(f=!0,a.$("#rentPrice").removeClass("a-size-base").addClass("a-size-medium"));
i&&(h.indexOf(c.value)!==-1?j():g(),a.$("#rentBoxMerchantDetails").show())})}});b.when("A","a-popover","ready").execute(function(a,c){var b=a.$;if(a.state("rentbox-common-page-state")){var f=b("#SSOFPopoverLink_rbb_content"),b=b("#SSOFPopoverLink_rbb");c.create(b,{position:"triggerBottom",inlineContent:f.html(),header:f.attr("data-title"),width:430,activate:"onclick"})}})})})(function(){var b=window.AmazonUIPageJS||P,a=b.attributeErrors;return a?a("RentalsPlatformDPXModulesAUIAssets"):b}());
/* ******** */
(function(a){a.execute(function(){})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("GoldboxUDPAssets"):a}());
/* ******** */
(function(a){a.execute(function(){})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("BabyRegistryDPAssets"):a}());
/* ******** */
